// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzQNhGYrKTFEECTbX3tUbdMVhKO99jkI',
    appId: '1:824217137422:web:777400d351ab922000675f',
    messagingSenderId: '824217137422',
    projectId: 'brotrachka',
    authDomain: 'brotrachka.firebaseapp.com',
    storageBucket: 'brotrachka.appspot.com',
    measurementId: 'G-NLFLYHLJT1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1e9pDwv_SKWX-ys0OoqYvksn2mOKo56k',
    appId: '1:824217137422:ios:2c46abdd3fb3313400675f',
    messagingSenderId: '824217137422',
    projectId: 'brotrachka',
    storageBucket: 'brotrachka.appspot.com',
    iosBundleId: 'com.example.brotrachka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1e9pDwv_SKWX-ys0OoqYvksn2mOKo56k',
    appId: '1:824217137422:ios:2c46abdd3fb3313400675f',
    messagingSenderId: '824217137422',
    projectId: 'brotrachka',
    storageBucket: 'brotrachka.appspot.com',
    iosBundleId: 'com.example.brotrachka',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jb43pmSEmA9lnRYXtgetb-zjEKjHmHw',
    appId: '1:824217137422:android:9c22ead3af9c18f000675f',
    messagingSenderId: '824217137422',
    projectId: 'brotrachka',
    storageBucket: 'brotrachka.appspot.com',
  );

}